<?php
/**
 * Поля для настройки FAQ
 *
 * @package Clinic_Prime
 * @version 1.0.0
 */
if (!defined('ABSPATH')) {
    exit;
}

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_68b983a4a892c',
	'title' => 'FAQ',
	'fields' => array(
		array(
			'key' => 'field_68b983a4819cc',
			'label' => '',
			'name' => 'faqs',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68b983ee819cd',
					'label' => 'Вопрос',
					'name' => 'q',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => 'br',
					'parent_repeater' => 'field_68b983a4819cc',
				),
				array(
					'key' => 'field_68b98409819ce',
					'label' => 'Ответ',
					'name' => 'a',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 1,
					'parent_repeater' => 'field_68b983a4819cc',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-faq',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68b67c31d00c8',
	'title' => 'Блоки',
	'fields' => array(
		array(
			'key' => 'field_68b67c31c6619',
			'label' => 'Редактор блоков',
			'name' => 'template_blocks',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_68b67cb07fad7' => array(
					'key' => 'layout_68b67cb07fad7',
					'name' => 'main',
					'label' => 'Main',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b67d1245832',
							'label' => 'Текст',
							'name' => 'mainSubTitle',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68b67cd690831',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Клиника психиатрии и неврологии нового уровня',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b67d3890832',
							'label' => 'Ссылка',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68b67d6390833',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'С опорой на науку и бережным отношением к каждому',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b67d7b90834',
							'label' => 'Изображение',
							'name' => 'img',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => 1920,
							'min_height' => 564,
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b67cb07faa1' => array(
					'key' => 'layout_68b67cb07faa1',
					'name' => 'approach',
					'label' => 'Подход',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b9f2b07faa2',
							'label' => 'Ссылка 1',
							'name' => 'link_1',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f2c07faa3',
							'label' => 'Ссылка 2',
							'name' => 'link_2',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f2d07faa4',
							'label' => 'Ссылка 3',
							'name' => 'link_3',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f2e07faa5',
							'label' => 'Ссылка 4',
							'name' => 'link_4',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f2f07faa6',
							'label' => 'Ссылка 5',
							'name' => 'link_5',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f3007faa7',
							'label' => 'Ссылка 6',
							'name' => 'link_6',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f3107faa8',
							'label' => 'Ссылка 7',
							'name' => 'link_7',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f3207faa9',
							'label' => 'Ссылка 8',
							'name' => 'link_8',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b684ebf1192' => array(
					'key' => 'layout_68b684ebf1192',
					'name' => 'features',
					'label' => 'Features',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b68f0746fb8',
							'label' => 'Features',
							'name' => 'features',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Добавить',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68b68f1946fb9',
									'label' => 'Изображение',
									'name' => 'img',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_68b68f0746fb8',
								),
								array(
									'key' => 'field_68b68f2646fba',
									'label' => 'Название',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => 2,
									'placeholder' => '',
									'new_lines' => 'br',
									'parent_repeater' => 'field_68b68f0746fb8',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b692b23c017' => array(
					'key' => 'layout_68b692b23c017',
					'name' => 'about',
					'label' => 'About',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b692c93c01b',
							'label' => 'Label',
							'name' => 'label',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Основательницы',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_68b692e63c01c',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Привет! <span>Это основательницы клиники «Справиться Проще» </span>Карина Истомина и Наташа Каданцева.',
							'tabs' => 'text',
							'media_upload' => 0,
							'toolbar' => 'full',
							'delay' => 0,
						),
						array(
							'key' => 'field_68b6932ced26d',
							'label' => 'Текст',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_68b6933fed26e',
							'label' => 'Страница',
							'name' => 'page',
							'aria-label' => '',
							'type' => 'page_link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'page',
							),
							'post_status' => '',
							'taxonomy' => '',
							'allow_archives' => 1,
							'multiple' => 0,
							'allow_null' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b692b23c101' => array(
					'key' => 'layout_68b692b23c101',
					'name' => 'about_new',
					'label' => 'About New',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b9f1a1a1011',
							'label' => 'Ссылка Карина Истомина',
							'name' => 'karina_link',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f1b9a1012',
							'label' => 'Ссылка Наташа Каданцева',
							'name' => 'natasha_link',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_68b9f1d2a1013',
							'label' => 'Ссылка "Подробнее о нас"',
							'name' => 'more_link',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b9421db3424' => array(
					'key' => 'layout_68b9421db3424',
					'name' => 'tags',
					'label' => 'Tags',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b9421db3429',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Что вас беспокоит?',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b9424fb342c',
							'label' => 'Выбрать теги',
							'name' => 'shoose_tags',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui_on_text' => 'Да',
							'ui_off_text' => 'Нет',
							'ui' => 1,
						),
						array(
							'key' => 'field_68b94277b342d',
							'label' => 'Теги',
							'name' => 'tags',
							'aria-label' => '',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_68b9424fb342c',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'doctor_diseases',
							'add_term' => 0,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'object',
							'field_type' => 'multi_select',
							'allow_null' => 0,
							'bidirectional' => 0,
							'multiple' => 0,
							'bidirectional_target' => array(
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b946ac51454' => array(
					'key' => 'layout_68b946ac51454',
					'name' => 'spec',
					'label' => 'Specialist',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b946ac51456',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '«Справиться Проще» — научно-популярный проект о ментальном здоровье',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b946d151459',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'С 2021 года вместе с гостями, психотерапевтами и врачами из наших выпусков снимаем стигму с психических расстройств. Если в программе мы рассказываем о способах помощи, то в клинике — оказываем ее.',
							'maxlength' => '',
							'rows' => 3,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b946f45145a',
							'label' => 'Специалисты',
							'name' => 'doctors',
							'aria-label' => '',
							'type' => 'relationship',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'doctors',
							),
							'post_status' => array(
								0 => 'publish',
							),
							'taxonomy' => '',
							'filters' => array(
								0 => 'search',
								1 => 'taxonomy',
							),
							'return_format' => 'object',
							'min' => '',
							'max' => '',
							'elements' => '',
							'bidirectional' => 0,
							'bidirectional_target' => array(
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b97a6916ba2' => array(
					'key' => 'layout_68b97a6916ba2',
					'name' => 'second_features',
					'label' => 'Features 2',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b97b1616ba6',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Каждый из наших специалистов',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b97a6916ba3',
							'label' => 'Features',
							'name' => 'features',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Добавить',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68b97a6916ba4',
									'label' => 'Изображение',
									'name' => 'img',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_68b97a6916ba3',
								),
								array(
									'key' => 'field_68b97a6916ba5',
									'label' => 'Название',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => 2,
									'placeholder' => '',
									'new_lines' => 'br',
									'parent_repeater' => 'field_68b97a6916ba3',
								),
								array(
									'key' => 'field_68b97b3016ba7',
									'label' => 'Описание',
									'name' => 'desc',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => '',
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_68b97a6916ba3',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b97fe574972' => array(
					'key' => 'layout_68b97fe574972',
					'name' => 'physician',
					'label' => 'Physician',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68b97fe574973',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Привет! Я&nbsp;<span>Денис Туряница,</span> главный врач клиники «Справиться Проще».',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68b9808974978',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Мы ценим качество и&nbsp;всегда открыты к диалогу.
Если у вас есть вопросы, замечания или жалобы — напишите мне. Мы подробно разберем ситуацию и вместе найдем решение.',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68b98713ba1dc' => array(
					'key' => 'layout_68b98713ba1dc',
					'name' => 'faq',
					'label' => 'FAQ',
					'display' => 'block',
					'sub_fields' => array(
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba4884900dd' => array(
					'key' => 'layout_68ba4884900dd',
					'name' => 'main_about',
					'label' => 'Main about',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba4884900de',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Доказательная <span>психиатрия и&nbsp;неврология</span> в Москве',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4884900e0',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Лечим так, как хотели бы, чтобы лечили нас: с уважением, вниманием и опорой на новейшие научные данные.',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4884900e1',
							'label' => 'Изображения',
							'name' => 'images',
							'aria-label' => '',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'insert' => 'append',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba4d3ac375b' => array(
					'key' => 'layout_68ba4d3ac375b',
					'name' => 'mission',
					'label' => 'Mission',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba4d3ac375c',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Наша миссия',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4d3ac375d',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Мы ценим качество и всегда открыты к диалогу.Если у вас есть вопросы, замечания или жалобы — напишите мне. Мы подробно разберем ситуацию и вместе найдем решение.',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba4d65c375f' => array(
					'key' => 'layout_68ba4d65c375f',
					'name' => 'history',
					'label' => 'History',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba4d65c3760',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'История создания',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4d65c3761',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 1,
						),
						array(
							'key' => 'field_68ba4d7dc3762',
							'label' => 'Видео',
							'name' => 'video',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'rows' => 3,
							'placeholder' => '',
							'new_lines' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba4db6c3763' => array(
					'key' => 'layout_68ba4db6c3763',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba4db6c3764',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Забота о самых маленьких',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4db6c3765',
							'label' => 'Описание',
							'name' => 'desc',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Четыре года назад Карина Истомина и Наташа Каданцева запустили свой первый проект — ютуб-канал «Справиться Проще». Они приглашали специалистов и гостей, которые рассказывали о своем непростом опыте, и видели, какой отклик это находит у зрителей.',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4db6c3766',
							'label' => 'Изображения',
							'name' => 'images',
							'aria-label' => '',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'insert' => 'append',
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba4e07c3767' => array(
					'key' => 'layout_68ba4e07c3767',
					'name' => 'media',
					'label' => 'Media',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba4e0ec3769',
							'label' => 'Заголовок',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Наше медиа о ментальном здоровье',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba4e15c376a',
							'label' => 'Медиа',
							'name' => 'media',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'min' => 0,
							'max' => 0,
							'collapsed' => 'field_68ba4e81c376c',
							'button_label' => 'Добавить',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68ba4e74c376b',
									'label' => 'Изображение',
									'name' => 'img',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_68ba4e15c376a',
								),
								array(
									'key' => 'field_68ba4e81c376c',
									'label' => 'Заголовок',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '70',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68ba4e15c376a',
								),
								array(
									'key' => 'field_68ba4e93c376d',
									'label' => 'Дата',
									'name' => 'date',
									'aria-label' => '',
									'type' => 'date_picker',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'display_format' => 'd.m.Y',
									'return_format' => 'd.m.Y',
									'first_day' => 1,
									'parent_repeater' => 'field_68ba4e15c376a',
								),
								array(
									'key' => 'field_68ba4fdfc376e',
									'label' => 'Ссылка',
									'name' => 'link',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68ba4e15c376a',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Добавить',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-parts/about.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68b948fdec03f',
	'title' => 'Доктора',
	'fields' => array(
		array(
			'key' => 'field_68b94bac6b4d0',
			'label' => 'Данные',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b95b6e2740d',
			'label' => 'Изображение',
			'name' => 'img',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_68b948fe843d9',
			'label' => 'Стаж',
			'name' => 'age_work',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Введите год начала',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 2000,
			'min' => 0,
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68b949686cf58',
			'label' => 'Цитата',
			'name' => 'quote',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 3,
			'placeholder' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_68b949be2ba6c',
			'label' => 'Особый интерес',
			'name' => 'tags_favorite',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68b94b182ba6f',
					'label' => 'Название',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68b949be2ba6c',
				),
				array(
					'key' => 'field_68b94b1f2ba70',
					'label' => 'Ссылка',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68b949be2ba6c',
				),
			),
		),
		array(
			'key' => 'field_68b94b84a05d3',
			'label' => 'Видео',
			'name' => 'video',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 4,
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_68b9531980e74',
			'label' => 'Ссылка на ТГ',
			'name' => 'tg',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68b94bd66b4d2',
			'label' => 'Фильтр',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b94af52ba6e',
			'label' => 'Что вас беспокоит?',
			'name' => 'tags_filter',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'doctor_diseases',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		//добавь сюда acf select для выбора специальности
		array(
			'key' => 'field_68va3db1ce182',
			'label' => 'Тип специалиста',
			'name' => 'specialist_type',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'psychologist' => 'Психолог',
				'clinical' => 'Клинический психолог',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_68va3db2ce184',
			'label' => 'Описание специалиста',
			'name' => 'specialist_description',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 3,
			'placeholder' => '',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_68ba3dbbce182',
			'label' => 'Специальность',
			'name' => 'spec_filter',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'doctor_specialty',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'object',
			'field_type' => 'multi_select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_68b94bbf6b4d1',
			'label' => 'Статьи',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b94beb6b4d3',
			'label' => 'Статьи',
			'name' => 'articles',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_68b9506be3075',
			'button_label' => 'Статья +',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68b94bf06b4d4',
					'label' => 'Изображение',
					'name' => 'img',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_68b94beb6b4d3',
				),
				array(
					'key' => 'field_68b9506be3075',
					'label' => 'Название',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68b94beb6b4d3',
				),
				array(
					'key' => 'field_68b95087e3076',
					'label' => 'Дата',
					'name' => 'date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd.m.Y',
					'return_format' => 'd.m.Y',
					'first_day' => 1,
					'parent_repeater' => 'field_68b94beb6b4d3',
				),
				array(
					'key' => 'field_68b950ace3077',
					'label' => 'Ссылка',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68b94beb6b4d3',
				),
			),
		),
		array(
			'key' => 'field_68b952a57d8f9',
			'label' => 'Записаться и Цены',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b952b97d8fa',
			'label' => 'Кнопка',
			'name' => 'btn',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Сохрание пост',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Записаться | от 8000 ₽',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68b953581638a',
			'label' => 'Первичный прием',
			'name' => 'cost_1',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68b9536f1638b',
			'label' => 'Вторичный прием',
			'name' => 'cost_2',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'doctors',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68b9a253e1659',
	'title' => 'Документы',
	'fields' => array(
		array(
			'key' => 'field_68b9a254d1d07',
			'label' => 'Документы',
			'name' => 'docs',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68b9a271d1d08',
					'label' => 'Тип',
					'name' => 'type',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'url' => 'URL',
						'pdf' => 'PDF',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_68b9a254d1d07',
				),
				array(
					'key' => 'field_68b9a2b5d1d09',
					'label' => 'Название',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68b9a254d1d07',
				),
				array(
					'key' => 'field_68b9a2cbd1d0a',
					'label' => 'URL',
					'name' => 'url',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_68b9a271d1d08',
								'operator' => '==',
								'value' => 'url',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68b9a254d1d07',
				),
				array(
					'key' => 'field_68b9a2dcd1d0b',
					'label' => 'PDF',
					'name' => 'pdf',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_68b9a271d1d08',
								'operator' => '==',
								'value' => 'pdf',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_68b9a254d1d07',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-parts/docs.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'featured_image',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68b99a4331180',
	'title' => 'Контакты',
	'fields' => array(
		array(
			'key' => 'field_68b99a437efbf',
			'label' => 'Почта',
			'name' => 'email',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'clinic@handlingbetter.ru',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68bab1e27efc1',
			'label' => 'Telegram',
			'name' => 'telegram',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68bab21b7efc2',
					'label' => 'Аккаунт',
					'name' => 'account',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Укажите с @ — вид: @username.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '@username',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68bab2357efc3',
					'label' => 'Ссылка',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => 'Например: https://t.me/username',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'https://t.me/username',
				),
			),
		),
		array(
			'key' => 'field_68b99a667efc0',
			'label' => 'Реквизиты',
			'name' => 'details',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68b99a8f7efc1',
					'label' => 'Название',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'ООО «Справиться Проще»',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68b99aa77efc2',
					'label' => 'ОГРН',
					'name' => 'ogrn',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'ОГРН: 1247700690808',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68b99abd7efc3',
					'label' => 'ИНН',
					'name' => 'inn',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'ИНН: 9701299000',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68b99aca7efc4',
					'label' => 'КПП',
					'name' => 'kpp',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'КПП: 770101001',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_68b99b64d3844',
			'label' => 'FAQ',
			'name' => 'faq',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Добавить',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68b99b6dd3845',
					'label' => 'Вопрос',
					'name' => 'q',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'rows' => 2,
					'placeholder' => '',
					'new_lines' => 'br',
					'parent_repeater' => 'field_68b99b64d3844',
				),
				array(
					'key' => 'field_68b99b77d3846',
					'label' => 'Ответ',
					'name' => 'a',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 1,
					'parent_repeater' => 'field_68b99b64d3844',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-parts/contacts.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'featured_image',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68b12613b2a09',
	'title' => 'Настройки',
	'fields' => array(
		array(
			'key' => 'field_68b1261355ea0',
			'label' => 'Header',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b160dc01edf',
			'label' => '',
			'name' => 'theme_header',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68b1692a1b9c9',
					'label' => 'Логотип',
					'name' => 'logo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_68b161a493ccf',
					'label' => 'Меню верхнее',
					'name' => 'top_bar',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui_on_text' => 'Показать',
					'ui_off_text' => 'Скрыть',
					'ui' => 1,
				),
				array(
					'key' => 'field_68b161f993cd1',
					'label' => 'Телефон',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '8 800 555 35 35',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68b1622093cd2',
					'label' => 'Записаться на прием',
					'name' => 'btn_appointment',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'Для указания в системе записи на прием используйте 2-ID - 
PC: "btn_appointment"
Mobile: "btn_appointment_mobile"',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui_on_text' => 'Показать',
					'ui_off_text' => 'Скрыть',
					'ui' => 1,
				),
			),
		),
		array(
			'key' => 'field_68b1670d895fa',
			'label' => 'Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b167ca57d16',
			'label' => '',
			'name' => 'theme_footer',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68b16719895fb',
					'label' => 'Логотип',
					'name' => 'logo',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_68b167ac57d15',
					'label' => 'Copy',
					'name' => 'copy',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '© {Y} Справиться проще',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_68b162b593cd4',
			'label' => 'Other',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b978efeb624',
			'label' => 'Страница врачей',
			'name' => 'theme_doctors_page',
			'aria-label' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'allow_archives' => 0,
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_68b1629d93cd3',
			'label' => 'Контакты',
			'name' => 'theme_contacts',
			'aria-label' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'allow_archives' => 0,
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_68b169f273f3e',
			'label' => 'Обработка персональных данных',
			'name' => 'theme_person_page',
			'aria-label' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'allow_archives' => 0,
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_68ba9c2b5d8a1',
			'label' => 'Почты для анкет',
			'name' => 'psi_form_emails',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Укажите email-адреса через запятую или с новой строки.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => 3,
			'placeholder' => 'mail@example.com, another@example.com',
			'new_lines' => '',
		),
		array(
			'key' => 'field_68b666145a71a',
			'label' => 'Social.Net',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_68b46a5b44891',
			'label' => 'Социальные сети',
			'name' => 'theme_social',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'tg' => 'Телеграм',
				'youtube' => 'YouTube',
				'yandex' => 'Yandex',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'multiple' => 1,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_68b665c158777',
			'label' => 'Телеграм',
			'name' => 'tg',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68b46a5b44891',
						'operator' => '==',
						'value' => 'tg',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68b665e158778',
			'label' => 'YouTube',
			'name' => 'youtube',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68b46a5b44891',
						'operator' => '==',
						'value' => 'youtube',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_68b665f558779',
			'label' => 'Yandex',
			'name' => 'yandex',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68b46a5b44891',
						'operator' => '==',
						'value' => 'yandex',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'clinic-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68bae751a1fa6',
	'title' => 'Специалисты',
	'fields' => array(
		array(
			'key' => 'field_68bae766e0eba',
			'label' => 'H1',
			'name' => 'header_h1',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_68bae78a5d9d4',
			'label' => 'Лид-абзац',
			'name' => 'header_lead',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-parts/doctors.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'featured_image',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68b9658084d80',
	'title' => 'Специальности',
	'fields' => array(
		array(
			'key' => 'field_68b9658042846',
			'label' => 'Цвет',
			'name' => 'color',
			'aria-label' => '',
			'type' => 'color_select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => '1 : <span style="width: 24px;height:24px;background:#059669"></span>
2 : <span style="width: 24px;height:24px;background:#05B4A0"></span>
3 : <span style="width: 24px;height:24px;background:#BC7DFF"></span>
4 : <span style="width: 24px;height:24px;background:#8B5CF6"></span>
5 : <span style="width: 24px;height:24px;background:#2E99BF"></span>',
			'default_value' => '',
			'allow_null' => 0,
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'doctor_specialty',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68ba81fe47ffc',
	'title' => 'Статьи',
	'fields' => array(
		array(
			'key' => 'field_68ba8268fea8a',
			'label' => 'H1',
			'name' => 'header_h1',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_68ba82a3fea8b',
			'label' => 'Лид-абзац',
			'name' => 'header_lead',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'text',
			'media_upload' => 0,
			'toolbar' => 'full',
			'delay' => 0,
		),
		array(
			'key' => 'field_68baddbb0ca88',
			'label' => 'Специализация',
			'name' => 'specialty',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'doctor_specialty',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_68ba81fef8137',
			'label' => 'Наполнение',
			'name' => 'blocks',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_68ba82d4fea8c' => array(
					'key' => 'layout_68ba82d4fea8c',
					'name' => 'content',
					'label' => 'Content',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba82d4fea8e',
							'label' => 'Текст',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba8314fea8f' => array(
					'key' => 'layout_68ba8314fea8f',
					'name' => 'promo',
					'label' => 'Promo',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68ba8338fea91',
							'label' => 'Изображение',
							'name' => 'img',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_68ba8349fea92',
							'label' => 'Текст',
							'name' => 'text',
							'aria-label' => '',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'rows' => 2,
							'placeholder' => '',
							'new_lines' => 'br',
						),
						array(
							'key' => 'field_68ba837dfea93',
							'label' => 'Ссылка',
							'name' => 'link',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba83a6fea94' => array(
					'key' => 'layout_68ba83a6fea94',
					'name' => 'spoillers',
					'label' => 'Spoilers',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68bad38d1c464',
							'label' => 'Spoilers',
							'name' => 'items',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Добавить',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68ba83bdfea96',
									'label' => 'Название',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'rows' => 2,
									'placeholder' => '',
									'new_lines' => 'br',
									'parent_repeater' => 'field_68bad38d1c464',
								),
								array(
									'key' => 'field_68ba83d2fea97',
									'label' => 'Описание',
									'name' => 'desc',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 1,
									'parent_repeater' => 'field_68bad38d1c464',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_68ba8517b3a1b' => array(
					'key' => 'layout_68ba8517b3a1b',
					'name' => 'prices',
					'label' => 'Prices',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_68bad587f6f29',
							'label' => 'Список',
							'name' => 'list',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'pagination' => 0,
							'min' => 0,
							'max' => 0,
							'collapsed' => 'field_68ba5c20892d5',
							'button_label' => 'Добавить',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_68bad587f6f2a',
									'label' => 'ID',
									'name' => 'id',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => 'Установите ID для формы записи',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 'article_1',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68bad587f6f29',
								),
								array(
									'key' => 'field_68bad587f6f2b',
									'label' => 'Название',
									'name' => 'name',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68bad587f6f29',
								),
								array(
									'key' => 'field_68bad587f6f2d',
									'label' => 'Цена на первиный прием',
									'name' => 'cost_1',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68bad587f6f29',
								),
								array(
									'key' => 'field_68bad587f6f2e',
									'label' => 'Цена на вторичный прием',
									'name' => 'cost_2',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_68bad587f6f29',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Добавить',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_68ba583390012',
	'title' => 'Услуги',
	'fields' => array(
		array(
			'key' => 'field_68ba5833892d1',
			'label' => 'Шаблон',
			'name' => 'template',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				1 => 'Доктора',
				2 => 'Услуги',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_68ba58b4892d2',
			'label' => 'Специальность',
			'name' => 'specialty',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68ba5833892d1',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'doctor_specialty',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'select',
			'allow_null' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_68ba5923892d3',
			'label' => 'Список',
			'name' => 'list',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_68ba5833892d1',
						'operator' => '==',
						'value' => '2',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_68ba5c20892d5',
			'button_label' => 'Добавить',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_68ba5bd4892d4',
					'label' => 'ID',
					'name' => 'id',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Установите ID для формы записи',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'service_1',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68ba5923892d3',
				),
				array(
					'key' => 'field_68ba5c20892d5',
					'label' => 'Название',
					'name' => 'name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68ba5923892d3',
				),
				array(
					'key' => 'field_68ba5c2a892d6',
					'label' => 'Подпись',
					'name' => 'caption',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68ba5923892d3',
				),
				array(
					'key' => 'field_68ba5c3c892d7',
					'label' => 'Цена на первиный прием',
					'name' => 'cost_1',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68ba5923892d3',
				),
				array(
					'key' => 'field_68ba5c5b892d8',
					'label' => 'Цена на вторичный прием',
					'name' => 'cost_2',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_68ba5923892d3',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'services',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );